# Site settings
title: Exploration
email: will@willdearman.com
description: > # this means to ignore newlines until "baseurl:"
  Boldly go...
baseurl: "/willdearman/" # the subpath of your site, e.g. /blog/
url: "http://willdearman.github.io" # the base hostname & protocol for your site
twitter_username: wtd
github_username:  willdearman

# Build settings
markdown: kramdown
