# Site settings
title: 				Exploration
tagline:			'Boldly go...'
description: 		'An experiment by Will Dearman'
paginate:            5

baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.willdearman.com" # the base hostname & protocol for your site
twitter_username: wtd
github_username:  willdearman

# Build settings
markdown: kramdown

# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty

# About/contact
author:
  name:              Will Dearman
  url:               https://twitter.com/wtd
  email:             will@willdearman.com

# Github Gems
gems:
  - jekyll-sitemap
  - jekyll-feed

# Custom vars
version:             0.5.1
